from pydantic import BaseModel, Field
from typing import List


class Action(BaseModel):
    """Defines a single atomic action for the robotic agent."""

    rationale: str = Field(..., description="Logical reason for this specific action.")

    task: str = Field(
        ...,
        description="The specific action to perform. Examples: 'cleaning', 'cooking', 'ironing', 'washing', 'drying', 'folding', 'sorting by color', 'setting thermostat', 'dimming lights', 'locking doors', 'updating shopping list', 'checking pantry inventory', 'feeding the dog', 'cleaning the litter box'.",
    )

    target_object: str = Field(
        ...,
        description="The physical object to act upon. Examples: 'shirt', 'floor', 'pasta', 'laundry basket', 'thermostat', 'light switch', 'door handle', 'shopping list', 'pantry inventory', 'dog food bowl', 'litter box'.",
    )

    priority: int = Field(
        default=1, ge=1, le=5, description="Urgency level: 1 (routine) to 5 (critical)."
    )


class MamiPlan(BaseModel):
    """The complete execution plan generated by the 'mami' reasoning engine."""

    overall_strategy: str = Field(
        ..., description="The high-level strategy Mami will follow to achieve the goal."
    )

    steps: List[Action] = Field(
        ..., description="A sequenced list of actions to fulfill the user's request."
    )
